camunda:
  client:
    mode: self-managed
    tenant-ids:
      - <default>
    auth:
      issuer: https://dave01.gke.c8sm.com/auth/realms/camunda-platform/protocol/openid-connect/token
      client-id: zeebe
      client-secret: xxx
    zeebe:
      enabled: true
      grpc-address: https://dave01.gke.c8sm.com
      rest-address: https://dave01.gke.c8sm.com/rest
      prefer-rest-over-grpc: true
      audience: zeebe-api
   #   scope: # optional
