camunda:
  client:
    auth:
      issuer: https://dave01.gke.c8sm.com/auth/realms/camunda-platform/protocol/openid-connect/token
      client-id: zeebe
      client-secret: xxx
    zeebe:
      base-url: https://dave01.gke.c8sm.com
      rest-address: https://dave01.gke.c8sm.com/rest
      grpc-address: https://dave01.gke.c8sm.com
      prefer-rest-over-grpc: false
    identity:
      audience: connectors
      base-url: https://dave01.gke.c8sm.com/auth
    mode: selfmanaged
  connector:
    polling:
      enabled: true
    webhook:
      enabled: true

operate:
  client:
    enabled: true
    profile: oidc
    url: https://dave01.gke.c8sm.com/operate
    base-url: https://dave01.gke.c8sm.com/operate
    auth-url: https://dave01.gke.c8sm.com/auth/realms/camunda-platform/protocol/openid-connect/token
    keycloak-url: https://dave01.gke.c8sm.com/auth
    audience: operate-api
    client-id: operate
    client-secret: xxx
