camunda:
  client:
    auth:
      issuer: https://dave01.gke.c8sm.com/auth/realms/camunda-platform/protocol/openid-connect/token
      client-id: zeebe
      client-secret: xxx
    zeebe:
      base-url: https://dave01.gke.c8sm.com
      rest-address: https://dave01.gke.c8sm.com/rest
      grpc-address: https://dave01.gke.c8sm.com
      prefer-rest-over-grpc: true
      audience: zeebe-api
    identity:
      audience: connectors
      base-url: https://dave01.gke.c8sm.com/auth
    mode: self-managed
  connector:
    polling:
      enabled: true
    webhook:
      enabled: true

# https://github.com/camunda-community-hub/camunda-operate-client-java?tab=readme-ov-file#how-to-build-the-client
operate:
  client:
    profile: oidc
    enabled: true
    base-url: https://dave01.gke.c8sm.com/operate
    auth-url: https://dave01.gke.c8sm.com/auth/realms/camunda-platform/protocol/openid-connect/token
    audience: operate-api
    client-id: connectors
    client-secret: xxx

