# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/
# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/configuration/

camunda:
  client:
    mode: saas
    auth:
      client-id: xxx
      client-secret: xxx
    cluster-id: xxx
    region: xxx

