# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options
camunda.client.mode=saas
camunda.client.auth.client-id=xxx
camunda.client.auth.client-secret=xxx
camunda.client.cluster-id=xxx
camunda.client.region=xxx
